apiVersion: v1
kind: PersistentVolume
metadata:
  name: localai-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/localai-models       # folder will be created automatically
  persistentVolumeReclaimPolicy: Retain
